# Generated by Django 4.0.3 on 2022-11-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=255)),
                ('question', models.IntegerField()),
                ('answer', models.IntegerField()),
                ('phone_number', models.CharField(max_length=255)),
            ],
        ),
    ]
