#!/root/virtualenv/bin/python

import pystrix

# Instanciamos el objeto agi para poder utilizar sus funciones.
agi = pystrix.agi.AGI()

agi.execute(pystrix.agi.core.verbose('Validando Identificacion', level=1))

agi.execute(pystrix.agi.core.answer                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             )                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                tt